### ISSUE TITLE
Want to add link

### ISSUE THREAD

**Issue by wow2006** [tzutalin/awesome-visual-slam#2]
Hello,

I want to share this link. I find it very helpful. I don't know which category to add it.
[Real Time Monocular 3D Reconstruction](https://fradelg.gitbooks.io/real-time-3d-reconstruction-from-monocular-video/content/index.html)

Best regards,
Ahmed Abdel Aal

**Comment by tzutalin** [comment]
I will add it later

**Comment by tzutalin** [comment]
@wow2006 ,
  I add it to a book category
https://github.com/tzutalin/awesome-visual-slam/commit/7ba19464c9abf3ce8a56499729ead57e3d7b2d0e
