### ISSUE TITLE
Some SLAM libraries are not included in the list

### ISSUE THREAD

**Issue by jarble** [tzutalin/awesome-visual-slam#7]
I noticed that [OpenVSLAM](https://github.com/xdspacelab/openvslam) and [DynaSLAM](https://github.com/BertaBescos/DynaSLAM) are not included on this list. Should they be listed here?

**Comment by tzutalin** [comment]
Sounds good. Could you help me update by sending a pull request

**Comment by tzutalin** [comment]
Fixed https://github.com/tzutalin/awesome-visual-slam/commit/f553d38b3aa7ac5e3d51deb43dfe0bc9ae6bd0b9
